version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master_node
    networks:
      - my_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
